name: Review app

on:
  pull_request:
    types: [closed]

jobs:
  remove_review_app:
    name: Request destruction
    concurrency: deploy-${{ github.event.pull_request.number }}
    runs-on: ubuntu-latest
    steps:
      - name: Remove review app request
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: "${{ github.event.pull_request.number }}",
              name: 'review app'
            })
