name: Review app

on:
  pull_request:
    types: [closed]

jobs:
  remove_review_app:
    name: Remove on close
    concurrency: deploy-${{ github.event.pull_request.number }}
    runs-on: ubuntu-latest
    steps:
      - name: Delete environment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: "preview-${{ github.event.pull_request.number }}",
              name: 'review app'
            })
