name: Deploy

on:
  push:
    tags:
      - v**

jobs:
  deploy_staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment: staging
    defaults:
      working-directory: infra
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init
      - run: terraform apply -auto-approve
  deploy_production:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production
    needs: [deploy_staging]
    defaults:
      working-directory: infra
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init
      - run: terraform apply -auto-approve
