name: Deploy

on:
  push:
    tags:
      - v**

jobs:
  deploy_staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment: staging
    env:
      TF_WORKSPACE: tf-demo-staging
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init -input=false
      - run: terraform apply -auto-approve -input=false
  deploy_production:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production
    needs: [deploy_staging]
    env:
      TF_WORKSPACE: tf-demo-production
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init -input=false
      - run: terraform apply -auto-approve -input=false
