name: Deploy review app

on:
  pull_request:
    types: [unlabeled]

jobs:
  destroy_review_app:
    name: Destroy review app
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.event.label.name == 'review app'
    environment: preview-${{ github.event.pull_request.number }}
    env:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init -input=false
      - run: terraform workspaces select tf-demo-preview-${{ github.event.pull_request.number }}
      - run: terraform destroy -auto-approve -input=false
